### ISSUE TITLE
circuit and document has not been updated for PB3 PB5 reverse issue

### ISSUE THREAD

**Issue by SHIGEMAL** [isparkes/ArdunixNix6#2]
Finally I understand current situation of my board.
Software has been updated for fixed PCB and PB3 must be tied with Tick LED as PWM usage.
Solution is following change on PCB.

PB5 to Tick LED Driver line cut.
PB3 to 74141 Digit D line cut
wired with PB5 and 74141 Digit D
wired with PB3 and Tick LED driver line.

**Comment by SHIGEMAL** [comment]
It was based on rev1 hardware. Code was released for Rev1

**Comment by isparkes** [comment]
In fact, you have made your Rev1 board into a Rev2 board! The change in the outputs was because I wanted to make the "tick" LED PWM able.

PB5/pin 19/Arduino pin 13 for historical reasons was the tick LED, because the software was developed on an Arduino UNO, and the on board LED is on that pin.

PB3/pin 17/Arduino pin 11 is PWM capable, but was used to drive the 74141, which does not need PWM.

Between Rev1 and Rev2, I swapped them. Rev3 and Rev4 keeps the Rev2 pin out.

Thanks for all the help!

Regards

Ian

**Comment by SHIGEMAL** [comment]
Dear Ian

Thanks for your clarification.
On my side, I only have your document and source code.
And I have understood what you had done change on board with reason.
On My clock project, LED and SWITCH are located on top of case.

http://www.techno-web.org/openlab/2016/03/26/%E3%83%8B%E3%82%AD%E3%82%B7%E3%83%BC%E7%AE%A1%E6%99%82%E8%A8%88%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86/

pictures are attached.

regards
Shigemal

**Comment by isparkes** [comment]
Hi Shigemal

I very much like your camp, it is great to involve young people in
technology.

I would like to support you somehow. What would help you? I could send you
some PCBs in latest revision - no software problems ;)

If you wish to make boards for yourself, I could let you have the Eagle
files, but to be kept within your camp and not distributed publicly. Also
PCB design is an art which young people could learn from.

Regards

Ian

**Comment by SHIGEMAL** [comment]
Hello Ian

Thanks for your offering.
Last year I had retired my jobs in Semiconductor technology application 
engineer.
It was 16 years from 1999. As you may know about CDMA giant.
Giving support to Japanese customer from US and worldwide team were very 
exciting business.
Even though application usage were not leading edge. So company had 
gained leading edge application usage learned from customer and put into 
chip set design with additional research result.
So customer had gained good chip-set from company. I had spent days from 
CDMA into LTE age as high-end cellular to high-end smart-phone.
Someday I have felt some feeling as customer cannot understand our 
suggestion or consulting. It means customer's knowledge has been downed 
with our support.
In addition, earthquake and Tsunami attack to TOHOKU and FUKUSHIMA issue 
makes me something works for future.
My 1st project for youth were Geiger counter kit workshop that was 
designed by my friend.
This activity make impress me a lot.
So I had started camp from 2012 March as 4 years ago for every weekend 
activity.
I had spent resource from my income as compensate TAX but it is still 
enough for TAX payment.
3 years activity makes good enough camp space as open workshop lab for 
youth.
This place is located some countryside area near by my technical college.
Now Maker's activity as Arduino or Raspberry PI etc. So camp has such 
things also.
PCB milling machine is good for countryside because no chemical issue 
has been considered.
3D Printer or laser cutter are offered but little bit subset.

After retirement I am thinking about next step.
I have good friend who had similar experience and good concerning for 
youth education.
Electronic tools Open Laboratory are named for this activity with him.

Soldering and Programming are good exercise for youth.
Even no source code, circuit reading and software design can be done as 
exercise. :-P

Please take look my camp site but sorry it was not written in English.
I shall consider for update as international for Japanese youth who will 
work for worldwide.

regards
Shigemal
