### ISSUE TITLE
latest code for Rev1 (V0008) shows Hours display digit opposite.

### ISSUE THREAD

**Issue by SHIGEMAL** [isparkes/ArdunixNix6#3]
It may shows some code fix has not been merged for this code.
I have fixed SW as HW assignment of Rev1.

**Comment by isparkes** [comment]
I'm not going to update the Rev1 code any more. Now that you have updated the board hardware, I think your issue has been solved (by you).

**Comment by isparkes** [comment]
Closed

**Comment by SHIGEMAL** [comment]
Dear Ian

Yes, my case has been fixed and also extra board also modified as rev2.
Thanks for your help.
I could confirm my point by you.

Regards

iPod$B$+$iAw?.(B $B@>;3LP4](B

2016/04/15 15:36$B!"(BIan Sparkes notifications@github.com $B$N%a%C%;!<%8(B:
