### ISSUE TITLE
Instruction-Manual Link not working

### ISSUE THREAD

**Issue by Fisico** [isparkes/ArdunixNix6#4]
Hello,

The instruction-manual link for "Rev4V42" is not working(Readme File).
[http://www.open-rate.com/Downloads/NixieClockInstructionManualRev4V42.pdf](http://www.open-rate.com/Downloads/NixieClockInstructionManualRev4V42.pdf)

**Comment by isparkes** [comment]
Thanks for that, it should be fixed now.

If you have the version with 3k resistors instead of 2k7 resistors, it is here:

[http://www.open-rate.com/Downloads/NixieClockInstructionManualRev4V42a3k.pdf](url)
